### ISSUE TITLE
Clarification about Faye

### ISSUE THREAD

**Issue by actsasbuffoon** [jasonm/wizards#1]
For people who aren't familiar with Faye, you may want to point out that you have to start the Faye server first. Otherwise the user will just get a message that "Faye is not defined" since the Faye server is responsible for providing the JS file.

Something like "rackup faye/config.ru -s thin -E production" should work.

**Comment by jasonm** [comment]
Hey Michael, good point - I included a `Procfile` but as that's not super standard, this could be made more clear in the README!

**Comment by jasonm** [comment]
Noted in a5a139dcfef945824ba29b822fc9f86378e321b8
